version: '3.3'

services:
  react:
    container_name: react
    build: ./IE-Project-React
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://localhost:8080/ca3
    depends_on:
      - java_server
  java_server:
    container_name: java_server
    build: ./IE-Project1
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    depends_on:
      - sql
  sql:
    container_name: sql
    image: mysql:8.0.16
    volumes:
      - /home/m0hammad/Archive/uni/Term8/ie/IE-Docker/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - NODE_ENV=development
      - MYSQL_ROOT_PASSWORD=pass123
      
